### ISSUE TITLE
Duplicated calls inside a while without a `yield return null`

### ISSUE THREAD

**Issue by mayo-nesso** [sebas77/Svelto.Tasks#7] opened 2017-11-14 22:23 UTC
Hi, I have a weird little problem running a Coroutine that has a loop and a `yield return new WaitForSeconds` inside. 
For some reason, if I don't include a `yield return null` the code inside the loop will be executed twice.

Unity version : `2017.1.2f1`

Source code: 
```
public class SimpleMono : MonoBehaviour
{
        private void Start()
        {
            TaskRunner.Instance.Run(TestTwice());
        }

        private IEnumerator TestTwice() 
        {
            Debug.Log("TestTwice Loop: start ");
            int counter = 0;

            while (true) 
            {
                Debug.Log("TestTwice Loop: Time " + Time.time + " C: " + counter);
                counter++;

                yield return new WaitForSeconds(1f);

                // ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! 
                // Adding "yield return null"  a loop. 
                // Without this, after execute `yield return new WaitForSeconds` in the loop, everything is executed twice !!! 
                // yield return null;
                // ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !               
            }
        }
}
```
Output: 
> 
> TestTwice Loop: start 
> TestTwice Loop: Time 0 C: 0
> TestTwice Loop: Time 1.007233 C: 1
> TestTwice Loop: Time 1.007233 C: 2
> ...

StackTrace of those repeated logs/calls.: 
 1. Same Time Counter Value = 1

> TestTwice Loop: Time 1.007233C: 1
> UnityEngine.Debug:Log(Object)
> Presentation.Temporal.FirstLoad.<TestTwice>c__Iterator1:MoveNext() (at Assets/Scripts/Presentation/Temporal/FirstLoad/FirstLoadController.cs:88)
> Svelto.Tasks.SerialTaskCollection:RunTasks() (at Assets/Plugins/Svelto/TaskRunner/SerialTaskCollection.cs:63)
> Svelto.Tasks.SerialTaskCollection:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/SerialTaskCollection.cs:42)
> Svelto.Tasks.Internal.CoroutineEx:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/CoroutineEx.cs:33)
> Svelto.Tasks.Internal.PausableTask:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/PausableTask.cs:121)
> Svelto.Tasks.Internal.<GetEnumerator>c__Iterator0:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/Runners/UnityCoroutineRunner.cs:225)
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

 2. Same Time Counter Value = 2
> TestTwice Loop: Time 1.007233C: 2
> UnityEngine.Debug:Log(Object)
> Presentation.Temporal.FirstLoad.<TestTwice>c__Iterator1:MoveNext() (at Assets/Scripts/Presentation/Temporal/FirstLoad/FirstLoadController.cs:88)
> Svelto.Tasks.SerialTaskCollection:RunTasks() (at Assets/Plugins/Svelto/TaskRunner/SerialTaskCollection.cs:63)
> Svelto.Tasks.SerialTaskCollection:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/SerialTaskCollection.cs:42)
> Svelto.Tasks.Internal.CoroutineEx:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/CoroutineEx.cs:33)
> Svelto.Tasks.Internal.PausableTask:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/PausableTask.cs:121)
> Svelto.Tasks.MonoRunner:ExecuteFirstTaskStep(IPausableTask) (at Assets/Plugins/Svelto/TaskRunner/Runners/MonoRunner.cs:55)
> Svelto.Tasks.MonoRunner:StartCoroutine(IPausableTask) (at Assets/Plugins/Svelto/TaskRunner/Runners/MonoRunner.cs:44)
> Svelto.Tasks.Internal.<GetEnumerator>c__Iterator0:MoveNext() (at Assets/Plugins/Svelto/TaskRunner/Runners/UnityCoroutineRunner.cs:226)
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Thanks !

**Comment by sebas77** [comment] 2017-11-16 10:26
hey thanks a lot for reporting a bug! I will check it ASAP!

**Comment by sebas77** [comment] 2017-12-25 00:43
Sorry I had to take so long to test this. My current test is like this:

 while (counter < 2)
            {
                counter++;

                yield return new WaitForSeconds(1f);

                Debug.Log(counter);
            }

and it correctly prints 1 and 2 only. Does it mean that the new version I am going to commit soon is fixed now?

**Comment by sebas77** [comment] 2017-12-25 11:48
I tested it with the latest version and I cannot reproduce it, let me know if it still happens to you

**Closed as completed by sebas77** 2017-12-25 11:48 UTC

**Comment by mayo-nesso** [comment] 2017-12-25 19:39
Thanks for the fix! :)
If I see an issue I will let you know !!
